version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/myproject
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 300
  AfterInstall:
    - location: scripts/setup_virtualenv.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
